name: GitHub Labeler

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Sync labels & Create Missing Labels
        uses: crazy-max/ghaction-github-labeler@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: '.github/labels.yml'
          skip-delete: true

      - name: Apply labels to PRs and Issues
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
